name: deploy

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    uses: laravel-chronicle/.github/.github/workflows/build.yml@51438c15798d323d564ae6dad40dbcc2ccb0ca39 # main
    with:
      image: 'ghcr.io/laravel-chronicle/docs'
      dockerfile: './Dockerfile'
      context: '.'

  cleanup:
    needs: [build-and-push]
    uses: laravel-chronicle/.github/.github/workflows/cleanup.yml@b6b15e48589b8d2ac37a1a9c08ec2290c090a93d # main
    with:
      package_name: 'docs'
      package_type: 'container'
      min_versions_to_keep: 3

  ssh-and-pull:
    needs: [build-and-push]
    uses: laravel-chronicle/.github/.github/workflows/pull.yml@e0e5ca059edf7b288bc64bccdf98f0090b24eb15 # main
    with:
      directory: '/home/sites/docs'
      compose_file: 'https://raw.githubusercontent.com/laravel-chronicle/docs/refs/heads/main/docker-compose.yml'
    secrets: inherit
